packages:
  - '.'
  - 'playground'
  - 'docs'
allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: false
  esbuild: false
  lefthook: true
  sharp: false
  unrs-resolver: false
  vue-demi: false
shamefullyHoist: true
patchedDependencies:
  shadcn-docs-nuxt: patches/shadcn-docs-nuxt.patch
